namespace EgourmetAPI.Model
{
    public class Orcamentos
    {
        public int Emp_Codigo { get; set; }
        public int Orc_Codigo { get; set; }
        public string Orc_Ano { get; set; }
        public string Conta_Codigo { get; set; }
        public int Condic_Codigo { get; set; }
        public int Trans_Codigo { get; set; }
        public DateTime Orc_Data { get; set; }
        public int Fun_Codigo { get; set; }
        public int Cli_Codigo { get; set; }
        public DateTime Orc_Data_Confirmacao { get; set; }
        public float Orc_Subtotal { get; set; }
        public string Orc_Observacoes { get; set; }
        public float Orc_Total { get; set; }
        public float Orc_Desconto { get; set; }
        public float Orc_Totitems { get; set; }
        public int Orc_Qdeparcelas { get; set; }
        public string Orc_Notafical { get; set; }
        public float Orc_Imposto { get; set; }
        public string Cfop { get; set; }
        public string Cancelado { get; set; }
        public int Formpgto_Codigo { get; set; }
        public int Mov_Codigo { get; set; }
        public int Preorc_Codigo { get; set; }
        public DateTime Orc_Dt_Cancela { get; set; }
        public DateTime Orc_Data_Emissao { get; set; }
        public DateTime Orc_Data_Saida { get; set; }
        public int Orc_Pdv { get; set; }
        public float Orc_Totprod { get; set; }
        public float Orc_Totserv { get; set; }
        public float Orc_Vlriss { get; set; }
        public float Orc_Vlrpis { get; set; }
        public float Orc_Vlrcofins { get; set; }
        public float Orc_VlrIrrf { get; set; }
        public float Orc_Vlrinss { get; set; }
        public float Orc_Vlrcsll { get; set; }
        public string Orc_Memnota { get; set; }
        public int Orc_Pedido { get; set; }
        public string Remessa { get; set; }
        public string Entreg_Endereco { get; set; }
        public string Entreg_Numero { get; set; }
        public string Entreg_Bairro { get; set; }
        public string Entreg_Cidade { get; set; }
        public string Entreg_Uf { get; set; }
        public string Entreg_Fone1 { get; set; }
        public string Entreg_Fone2 { get; set; }
        public string ENTREG_Cep { get; set; }
        public string Entreg_Ref { get; set; }
        public string Entreg_Contato { get; set; }
        public string Entreg_Local { get; set; }
        public string Entreg_Compl { get; set; }
        public string Entreg_Referencia { get; set; }
        public string Condic_Obs { get; set; }
        public DateTime Liberado { get; set; }
        public string Orc_Contato { get; set; }
        public DateTime Dtentrega { get; set; }
        public DateTime Dtcancelado { get; set; }
        public string Hrcancelado { get; set; }
        public string Orc_Notafiscal { get; set; }
        public string Orc_Nfserie { get; set; }
        public string Nfse { get; set; }
        public string File_Xml_Nfe { get; set; }
        public DateTime Dt_Envio_Xml { get; set; }
        public string File_Xml_Cancelado { get; set; }
        public DateTime Dt_Cancelamento_Nfe { get; set; }
        public string Hora_Abertura { get; set; }
        public DateTime Orc_Data_Hora { get; set; }
        public string Orc_Fim_Hora { get; set; }
        public int Seq { get; set; }
        public float Perc_Comissao { get; set; }
        public float Vlr_Comissao { get; set; }
        public float Vlr_Acrescimo { get; set; }
        public float Perc_Desconto { get; set; }
        public string Mesa { get; set; }
        public string Orc_Hrultimo_Atendimento { get; set; }
        public string Numero_Nfce { get; set; }
        public string Serie_Nfce { get; set; }
        public string Orc_Notafiscal_Serie { get; set; }
        public float Totaproxtributo { get; set; }
        public string inscricaoestadual { get; set; }
        public string emissorinscricaoestadual { get; set; }
        public string Pc_Criou { get; set; }
        public int Via { get; set; }
        public string Pc_Encerrou { get; set; }
        public string Nfe_Tp_Doc { get; set; }
        public string Nfe_Doc { get; set; }

    }
}
